### ISSUE TITLE
how can i login using reddit api in android application?

### ISSUE THREAD

**Issue by Slake07** [reddit/reddit#1254]
how can i login using reddit api for my android application.?

**Comment by xiongchiamiov** [comment]
As per [the recent announcement](https://www.reddit.com/r/redditdev/comments/2ujhkr/important_api_licensing_terms_clarified/), you should [use OAuth2 to handle reddit logins](https://github.com/reddit/reddit/wiki/OAuth2).

Since this is an issue tracker for bugs in reddit's website, I'm going to close this issue.  If you have any questions about how to hook up OAuth in your Android app, please feel free to consult the helpful folks over at [/r/redditdev](https://www.reddit.com/r/redditdev).
