### ISSUE TITLE
oAuth API responds with 401 Unauthorized on a valid OPTIONS request

### ISSUE THREAD

**Issue by jariz** [reddit/reddit#1285]
According to the specs, [authentication credentials must be removed from the OPTIONS request](http://www.w3.org/TR/cors/#cross-origin-request-with-preflight-0).
However, when doing this, the API will respond with 401 Unauthorized.
It will, however respond with 200 when you add the Authentication header, but this is against the specs.
This causes problems with CORS requests.

**With authorization** (non conforming to specs)

![](https://cloud.githubusercontent.com/assets/1415847/6834472/b765fec8-d334-11e4-93c9-343f672d73e7.png)

**Without authorization**  (conforming to specs)

![](https://cloud.githubusercontent.com/assets/1415847/6834478/c68bf240-d334-11e4-9865-941cc96d0586.png)

**Comment by trevorsenior** [comment]
I've [ran into this as well](https://www.reddit.com/r/redditdev/comments/2xdsix/application_only_oauth_for_browser_based/) using CORS. 

/u/kemitche 
> Looks like we have a bug in how we handle CORS for this flow. I definitely want you to be able to use app-only-OAuth for browser-based JS.

Here is the [relevant JSFiddle](http://jsfiddle.net/81t502s4/1/) that reproduces the problem (check the network tab in Chrome).

```
General 

Remote Address:198.41.209.142:443
Request URL:https://www.reddit.com/api/v1/access_token
Request Method:OPTIONS
Status Code:401 Unauthorized


Response Headers

cache-control:no-cache
cf-ray:1ccece2cfcc4020c-IAD
content-length:0
content-type:application/json; charset=UTF-8
date:Thu, 26 Mar 2015 00:40:39 GMT
server:cloudflare-nginx
set-cookie:__cfduid=d52d8496475a779cb15fb7e5ec4fa55e71427330439; expires=Fri, 25-Mar-16 00:40:39 GMT; path=/; domain=.reddit.com; HttpOnly
status:401 Unauthorized
version:HTTP/1.1
www-authenticate:Basic realm="reddit"
x-content-type-options:nosniff
x-frame-options:SAMEORIGIN
x-moose:majestic
x-ua-compatible:IE=edge
x-xss-protection:1; mode=block
```

I was going to start to look into this as it is holding back a major release of a project, but I won't have the time to until later next week due to course load. Even then it's iffy if I'll find a solution in the spare hours I'll find here and there.

**Comment by jariz** [comment]
@trevorsenior would be really cool if you were able to find some time to solve this as it's currently interfering with a project myself as well.

**Comment by trevorsenior** [comment]
I was going through the open issues on my own project and bumped into a related issue with client side JavaScript when trying to revoke tokens (https://github.com/trevorsenior/snoocore/issues/93). I made a [relevant post](https://www.reddit.com/r/redditdev/comments/2w8c2o/manually_revoking_an_access_token_with_an_app/) on this awhile back as well.

@jariz I'm still poking around here and there, but haven't sat down for a long session to debug this.

**Comment by kemitche** [comment]
I want to clarify something, as based on @jariz's initial wording I think there's some confusion.

Your JS can absolutely include authentication parameters in headers. It's the *browser's* job to strip those out when sending the pre-flight OPTIONS request. After the OPTIONS request clears successfully, your request will go through.

Currently, this fails because reddit is incorrectly blocking the OPTIONS request made by the browser.

**Comment by jrochkind** [comment]
I just found this after spending several hours banging my head against the code trying to do app-only/userless OAuth from the browser. 

No more comments or action since April 2015. 

If I understand right, there is no longer any non-auth app-only reddit API available fro the browser either -- you need to use OAuth. 

So is there currently any way to do app-only reddit API from the browser?  Is there anyone at reddit that is actually working on the API at all? If not, and there are no plans to do so, it might be wise to update the docs to make it clear that this use case is not supported, or link to this issue, or something. Took me quite a while to find this one, spent quite a while trying to make it work.

**Comment by 13steinj** [comment]
>  Is there anyone at reddit that is actually working on the API at all?

sometimes I'd think not at all. But, besided my annoying side comments,

@jrochkind, @kemitche fixed this on [the same day he commented](https://github.com/reddit/reddit/commit/92cc540e16a7d674619bcbd3b63d33112e240f39), this was just never closed.

There's a new bug now. The headers are being returned as lowercase instead of CamelCase as (at least) Chrome expects, so it doesn't detect them properly. I don't know _why_ they are being returned lowercase, as I can't see a change in the open source (this) repo that would be the cause.

**Comment by jariz** [comment]
Alright, I'll close this then.

**Comment by jrochkind** [comment]
Aha, thanks for closing!

In fact, my problem was the Disconnect plugin, specifically blacklisting reddit as a 'social tracker'. Doh, I lost hours to that before figuring out it was Disconnect!

Thanks all.
