### ISSUE TITLE
Wishlist: Support SVG in thumbnails

### ISSUE THREAD

**Issue by kaihendry** [reddit/reddit#1307]
I noticed https://github.com/reddit/reddit/blob/master/r2/r2/lib/media.py doesn't seem to have any support for SVGs. Would be nice if you could please support this scalable format.

Here is the canonical way it should be marked up IIUC:
https://html.spec.whatwg.org/multipage/semantics.html#rel-icon

**Comment by umbrae** [comment]
Hi there,

First administrative note: GitHub Issues are only for confirmed bugs. More on this here: https://github.com/reddit/reddit/blob/master/CONTRIBUTING.md

Second: We're unlikely to support third party SVGs of any kind in the near future due to the security risks involved. There are sanitization efforts ongoing but none that are up to our standards yet. You can see more context in the PR discussed here: https://github.com/reddit/reddit/pull/1290
