### ISSUE TITLE
"There's nothing here..." view goes under the footer.

### ISSUE THREAD

**Issue by ewintory** [reddit/reddit#1323]
See here: http://www.reddit.com/r/androiddev/comments/37150u/when_switching_from_listfragment_to_fragment_2/
![capture](https://cloud.githubusercontent.com/assets/6298084/7786075/65b9ccb8-01cd-11e5-897a-e41a8681402d.JPG)

**Comment by xiongchiamiov** [comment]
It's an issue with [the subreddit stylesheet](https://www.reddit.com/r/androiddev/about/stylesheet), specifically setting `postition:absolute` on `#noresults`.

You should contact the subreddit mods or, since [it appears that's an unmodified part of Naut](https://github.com/Axel--/Naut-for-reddit/blob/cc024c5c43e3977d056aba1912ef3438a00355ec/src/naut_src.css#L1820), file an issue on [Axel--/Naut-for-reddit](https://github.com/Axel--/Naut-for-reddit).

**Comment by ewintory** [comment]
@xiongchiamiov Got it, thx!
