### ISSUE TITLE
Upvotes/Downvotes don't get validated in archived posts when they are made via the API

### ISSUE THREAD

**Issue by pretodor** [reddit/reddit#1455]
Usually, when you try to upvote/downvote an archived post from the browser you'll get an error message saying:

> sorry, this has been archived and can no longer be voted on

but that validation isn't enforced when you do the same via the API.

Here are some screenshots showcasing the bug:

![screenshot_1](https://cloud.githubusercontent.com/assets/1466111/10950387/229286c4-8340-11e5-813f-6ac45bb3cd5e.png)

![screenshot_2](https://cloud.githubusercontent.com/assets/1466111/10950389/2294e3b0-8340-11e5-8c45-f78b59560acb.png)

![screenshot_3](https://cloud.githubusercontent.com/assets/1466111/10950390/229693fe-8340-11e5-9608-cd54c10a1397.png)

![screenshot_4](https://cloud.githubusercontent.com/assets/1466111/10950388/2294ce84-8340-11e5-8595-df5baa340c3c.png)

The bug allows people using mobile apps to access Reddit to change the number of upvotes in archived posts/comments.

**Comment by Pokechu22** [comment]
The votes don't actually change (it's fuzzed, so it may appear different on refreshing, but it isn't saved).  However, it should still give a message, as it is confusing when it does not.  (API clients should not have to manually check if it is archived before voting).

[Reference](https://github.com/reddit/reddit/blob/677e2223cfbccd7dfd5991e044413a0dc979a739/r2/r2/controllers/api.py#L2202).

**Comment by xiongchiamiov** [comment]
@Pokechu22 is correct.  To add, the reason an error message isn't returned in the api call is because all the controller does is shove the votes into a queue; by the time the queue processor looks up the information to determine if the vote is valid, we've long since returned the http response back to the client.  So, an api client should monitor the appropriate flag to prevent its users from trying to make those calls in the first place.
