### ISSUE TITLE
The mobile site is too large

### ISSUE THREAD

**Issue by 3rd3** [reddit/reddit#1638]
The mobile site appears to be larger than the desktop version. I measured 0.8MB compared to 1.9MB.

**Comment by ajacksified** [comment]
That's because you're counting the large preview images in card mode. When you change to thumbnail mode - which is a more accurate comparison - or if you look at the code delivered by the browser, without images - it's a different story. Furthermore, you only load assets _once_ on the mobile site, and everything is fetched over ajax later - so over a long browsing session, you'll actually load _less_ data.

CSS + HTML + JS: you're looking at 408k (desktop) vs 537k (mobile). All assets, including images, in compact mode - 570k vs 721k. It's larger, but not by much. As an aside, there are also some changes coming that will reduce m. to smaller than desktop.

For comparison, [this imgur page](http://imgur.com/gallery/3XXjKHV) is 1.7MB, of which only 600k are images. You could fit both the desktop and mobile sites inside of that.

**Comment by 3rd3** [comment]
> As an aside, there are also some changes coming that will reduce m. to smaller than desktop.

That is great to hear. Though comparing Reddit with Imgur really does not make a lot of sense (except when you only account for the masses of front page-only consumers). Imgur is exclusively for consuming lots of images and GIFs and nobody with a 200 MB per month data contract will go on Imgur (or on the Reddit front page).

I think you could care more about the small but influential target group of programmers, scientists, writers etc. that want a lot of text and little distraction by pictures, animations, hamburger menus etc. You won't lose a lot of users numerically if they leave, but culturally and intellectually.

I tried to do some more measurements on a page without images:

![_r_desktop](https://cloud.githubusercontent.com/assets/2372391/16716668/c8b131cc-4703-11e6-9723-c92b75c2d266.png)
![_r_mobile](https://cloud.githubusercontent.com/assets/2372391/16716716/02af885a-4705-11e6-829e-bf93560d2f76.png)

**Comment by ajacksified** [comment]
> I think you could care more about the small but influential target group of programmers, scientists, writers etc. that want a lot of text and little distraction by pictures, animations, hamburger menus etc. You won't lose a lot of users numerically if they leave, but culturally and intellectually.

This is a valid point - it's tough to make the product call, but I agree that there would be value in adding a setting to, say, disable thumbnails entirely. It's a feature we have to prioritize building with everything else- more subreddit customization, image uploads, etc- but I do think it's important to maintain as diverse a group as possible.
