### ISSUE TITLE
OAuth redirect URI mangled with fragment identifier present.

### ISSUE THREAD

**Issue by bemasher** [reddit/reddit#1687]
If the redirect uri for OAuth authentication contains a fragment identifier like in AngularJS apps:

`http://localhost/#/authorize`

The url we're redirected to when the user authorizes the app is mangled:

`http://localhost/?state=0123456789abcdef&code=abcdefg#/authorize`

**Comment by 13steinj** [comment]
While it's mangled, it kinda has to be.

Fragment identifier or not, the spec calls for anything after a fragment to be considered as that fragment. Including query params (as you can see, are returned with information). I haven't checked because I'm on mobile, but I be live urllibs urlparse / unparse does this as compensation to meet the spec.

**Comment by bemasher** [comment]
Yep, you're right. It looks like Angular's work-around for this is to:
Set `$locationProvider.html5mode(true)`
Add a base tag to specify the base url of the app: `<base href="/">`
And finally, add a rewrite rule to the webserver to direct everything in that app to `index.html`.

**Comment by kemitche** [comment]
Just for more context, the OAuth 2 spec prohibits fragment identifiers in the redirect URI: https://tools.ietf.org/html/rfc6749#section-3.1.2
