### ISSUE TITLE
Posting invalid HTML entities in a comment or self-post produces Error 500

### ISSUE THREAD

**Issue by pseudolobster** [reddit/reddit#438]
I found this out while mistakenly trying to use &emdash; instead of &amp;mdash;.

I was going to delete this once I realized my mistake, but as minor as this is, I still think it should be fixed, so that invalid entities are either filtered out or ignored. When I posted, I might not have realized what caused Error 500, and thought reddit in general was broken or something.

Very reproducible. Try posting &foo; in a comment or self post.

**Comment by JordanMilne** [comment]
This should be fixed with https://github.com/reddit/snudown/compare/0ffc96fda79a6efc2e6d523044f7200fb3219d54%7E8...0ffc96fda79a6efc2e6d523044f7200fb3219d54#diff-45c17c0a080fbe29e2b8ded8940aa1e8R22 and https://github.com/reddit/reddit/commit/9e09ac70da535e429ed305834bf0366b1b672ca4 . We're sticking with only entities that are valid in XHTML for compatibility, but unacceptable entities will be escaped. :sun_with_face:

**Comment by JonasOlson** [comment]
> We're sticking with only entities that are valid in XHTML for compatibility, but unacceptable entities will be escaped.

Why aren't all of them escaped? Why are we supposed to enter characters as HTML entities in the first place?

**Comment by JordanMilne** [comment]
>Why are we supposed to enter characters as HTML entities in the first place?

You don't really need to. It's just been a feature of sundown (and thus snudown) for a long time, and some people would rather do `&bull;` rather than figure out how to put a &bull; in verbatim.
