### ISSUE TITLE
Un-friend deleted users

### ISSUE THREAD

**Issue by lazytype** [reddit/reddit#959]
From: http://www.reddit.com/r/bugs/comments/1v9m9x/unable_to_unfriend_a_deleted_user/

"When a friend deletes their account their posts still show up in /r/friends . As far as I know there's no way to make them not show up in /r/friends because you can't unfriend them. There's no way to unfriend them since deleted users' pages don't have a remove friends button and the friends preference page doesn't list them as an option to remove as a friend."

**Comment by lazytype** [comment]
Looks resolved

**Comment by opeeba** [comment]
I seem to be affected by this bug. I have more than 100 posts from [deleted] users in my friends feed that have not been removed.

**Comment by phazei** [comment]
AFAIK, no old posts have been deleted.  In my friends feed, I have posts from deleted accounts that are well over a year old.

**Comment by 13steinj** [comment]
@phazei I don't know if the issue you claim exists, as I haven't tested it, but based on a cursory look, I assume it does. But there's two solutions:

1. @Deimos is working on making deleted users automatically remove themselves from friends lists, subscribers, banned lists, and whatnot. This would solve the overasting problem.


2. The first and last highlighted lines [here](https://github.com/reddit/reddit/blob/267e93e8ae7363d9dd4085d0e0f4b1ef2e97f639/r2/r2/models/subreddit.py#L1577-L1586) define the lines that the content of which users the content comes from. I don't recall what data structure `_byID` returns when getting more than one ID, but to be simple, removing any accounts in that data set who have a `_deleted` value of `True` would suffice.

**Comment by Deimos** [comment]
@phazei that's very strange, because when a user deletes their account, removing it from friends is one of the only cleanup tasks that does already get done: https://github.com/reddit/reddit/blob/master/r2/r2/models/account.py#L501-L506

The fix @13steinj was referring to was mostly for all the other ones it doesn't do, like removing the user from moderator lists, contributor lists, etc.

@phazei - is your account on reddit with the same username? I can check and see if you've got some deleted users left over in your list somehow.

**Comment by phazei** [comment]
@Deimos yes, same username

**Comment by Deimos** [comment]
@phazei Thanks, it looks like it's due to the cleanup job occasionally taking too long and timing out, which leaves it incomplete. So when that happens, the user doesn't get removed from all friends lists, and you end up with deleted users still in the list. I'm going to move this cleanup into a separate job, so that it shouldn't time out any more.

**Comment by phazei** [comment]
@Deimos 
Just a FYI, those deleted friend are still there

**Comment by Deimos** [comment]
@phazei weird, should definitely be getting cleaned up. I'll take a look.

**Comment by Deimos** [comment]
@phazei I manually cleaned up a couple more deleted users that it looks like were still in your friends, do things look correct now?

**Comment by phazei** [comment]
Almost all of them.  There's "lily_tiger" left.  They were still listed in the friends page, I hit remove, and now they're removed, but still listing on the friend feed.  Their account is also deleted.  Not sure if that'll take a bit to update, or if it needs some intervention.

**Comment by Deimos** [comment]
Ah, that account is banned, not deleted. We're not automatically removing banned users (but we probably should, in some cases).

**Comment by iwanttobleaf** [comment]
I have a deleted/banned account stuck under friends as well. My user name on reddit is 'iwanttobleaf' can you help me with that, too, @Deimos?

**Comment by Deimos** [comment]
@iwanttobleaf I just deployed a new change that should hide those accounts' posts from your /r/friends now, can you take a look and confirm for me? @phazei I think the banned account should be hidden from yours as well now too.

**Comment by iwanttobleaf** [comment]
It is gone now. Thank you so much! I will let you know if it should reappear again.
